## Numpy

###     Creating Array

1-D array

In [7]:
import numpy as np

a = np.array([2,3,4])
print(a)
print(type(a))

[2 3 4]
<class 'numpy.ndarray'>


2-D array

In [10]:
b = np.array([[2,4,7],[1,7,2]])
print(b)
print(type(b))

[[2 4 7]
 [1 7 2]]
<class 'numpy.ndarray'>


3-D array

In [11]:
c =  np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(c)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


checking dimension

In [12]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


higher dimension

In [14]:
arr = np.array([1, 2, 3, 4], ndmin=9)

print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[[[[[1 2 3 4]]]]]]]]]
number of dimensions : 9
